info:
  description: Royal College of Paediatrics and Child Health Digital Growth Charts
  license:
    name: GNU Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  title: RCPCH Digital Growth Charts API
  version: 0.0.3
openapi: 3.0.2
paths: {}
servers:
- description: RCPCH Production API Gateway
  url: https://api.rcpch.ac.uk/
- description: Your local development API
  url: https://localhost:5000/
