openapi: 3.0.0

info:
  version: 0.0.2
  title: Royal College of Paediatrics and Child Health Digital Growth Charts API
  description: API for calculation of growth parameters
  termsOfService: dev.rcpch.ac.uk
  contact: 
    name: API Support
    url: dev.rcpch.ac.uk
    email: support@example.com
  license:
    name: GNU Affero General Public License,
    url: https://www.gnu.org/licenses/agpl-3.0.en.html

servers:
  - url: 'https//api.rcpch.ac.uk/'
    description: 'RCPCH Production API Gateway'

paths:
  ### MULTIPLE CALCULATIONS
  /ukwho/calculations:
    post:
    summary: 'Calculates multiple digital growth chart parameters'
    parameters:
      - name: birth_date
        in: header
        description: date of birth of the patient in YYYY-MM-DD ISO8601 format
        required: true
        schema:
            type: string
            format: date

      - name: observation_date
        in: header
        description: The date that the measurement was taken, in YYYY-MM-DD ISO8601 format
        required: true
        schema:
            type: string  
            format: date

      - name: height_in_cm
        in: header
        description: The height of the patient, which MUST be in centimetres to get correct results.
        required: false
        schema:
            type: number

      - name: weight_in_kg
        in: header
        description: The weight of the patient, which MUST be in kilograms to get correct results.
        required: false
        schema:
            type: number

      - name: head_circ_in_cm
        in: header
        description: > 
            The head circumference (also described as occipito-frontal circumference) of the patient,
            which **must** be in centimetres to get correct results.
        required: false
        schema:
            type: number

      - name: sex
        in: header
        description: The sex of the patient, which can either be 'male' or 'female'
        required: true
        schema:
            type: string
            enum: ['female', 'male']

      - name: gestation_weeks
        in: header
        description: >
            The number of completed weeks of gestation at which the patient was born.
            This enables Gestational Age correction if the child was not born at term.
            See also the other parameter `gestation_days` - both are usually required.
        required: false
        schema:
            type: number

      - name: gestation_days
        in: header
        description: >
            The number of additional days _beyond the completed weeks of gestation_ at which the patient was born.
            This enables Gestational Age correction if the child was not born at term. See also the other parameter
            `gestation_weeks` - both are usually required.
        required: false
        schema:
            type: number

    responses:
      '200':
        description: 'Calculated measurements'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement'
      default:
        description: Unexpected error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'

  ### SINGLE CALCULATION
  /ukwho/calculation:
    post:
    summary: Returns a single calculation for weight-centile, height-centile, ofc-centile or BMI-centile.
    description: >
      This endpoint accepts a patient observation, and a measurement_method
    parameters:

      - name: birth_date
        in: header
        description: date of birth of the patient in YYYY-MM-DD ISO8601 format
        required: true
        schema:
            type: string
            format: date

      - name: observation_date
        in: header
        description: The date that the measurement was taken, in YYYY-MM-DD ISO8601 format
        required: true
        schema:
            type: string  
            format: date

      - name: measurement_method
        in: header
        description: The type of measurement performed ('height', 'weight', 'bmi' or 'ofc') on the infant or child. The value 
            is supplied as observation_value. The measurements represent height in cm, weight in kg, body mass index in kg/m² and occipitofrontal circumference (head circumference) in cm.
        required: true
        schema:
            type: string
            enum: ['height', 'weight', 'bmi', 'ofc']

      - name: observation_value
        in: query
        description: The value of the measurement supplied. Used in conjunction with type of measurement performed ('height', 'weight', 'bmi' or 'ofc') on the infant or child.
        required: true
        schema:
            type: number

      - name: sex
        in: header
        description: The sex of the patient, which can either be 'male' or 'female'
        required: true
        schema:
            type: string
            enum: ['female', 'male']

      - name: gestation_weeks
        in: header
        description: >
            The number of completed weeks of gestation at which the patient was born.
            This enables Gestational Age correction if the child was not born at term.
            See also the other parameter `gestation_days` - both are usually required.
        required: false
        schema:
            type: number

      - name: gestation_days
        in: header
        description: >
            The number of additional days _beyond the completed weeks of gestation_ at which the patient was born.
            This enables Gestational Age correction if the child was not born at term. See also the other parameter
            `gestation_weeks` - both are usually required.
        required: false
        schema:
            type: number

  ### CHART DATA
  /ukwho/chart_data:
    get:
    summary: Returns chart plotting data 

  ### SPREADSHEET UPLOAD
  /ukwho/spreadsheet:

  ### GROWTH REFERENCES
  /utilities/references:
    get:
      summary: Returns a JSON object containin details of all the growth references that we have collected as part of the Digital Growth Charts project
    responses:

  ### INSTRUCTIONS
  /utilities/instructions:


components:
  schemas:
    Measurement:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string